name: 'Setup NativeScript'
description: 'A GitHub Action to setup the NativeScript development environment on Windows, Linux and MacOSX.'
author: 'hrueger'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'download-cloud'  
  color: 'blue'
