name: "Build & Test"

on: [push]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update submodules
      run: git submodule init && git submodule update
    - run: |
        npm install
        npm run all
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
      fail-fast: false
    name: Test on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v1
    - uses: ./
    - name: NativeScript Doctor
      run: ns doctor

  testDemoAndroid:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    name: Build Android on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v1
    - uses: ./
    - name: Clone a NativeScript Demo App
      run: git clone https://github.com/hrueger/nativescript-angular-template
    - name: Install dependencies
      run: sudo npm install
      working-directory: nativescript-angular-template
    - name: Build NativeScript Demo App
      run: ns build android
      working-directory: nativescript-angular-template

  testDemoAndroidWindows:
    name: Build Android on windows-latest
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
    - name: Clone a NativeScript Demo App
      run: git clone https://github.com/hrueger/nativescript-angular-template
    - name: Install dependencies
      run: npm install
      working-directory: nativescript-angular-template
    - name: Build NativeScript Demo App
      run: ns build android
      working-directory: nativescript-angular-template

  testDemoiOS:
    name: Build iOS on MacOSX
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
    - name: Clone a NativeScript Demo App
      run: git clone https://github.com/hrueger/nativescript-angular-template
    - name: Install dependencies
      run: npm install
      working-directory: nativescript-angular-template
    - name: Build NativeScript Demo App
      run: ns build ios
      working-directory: nativescript-angular-template
          