name: "Build & Test"

on: [push]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
    name: Test on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v1
    - uses: ./
    - name: TNS Doctor
      run: tns doctor

  testDemoAndroid:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    name: Build Android on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v1
    - uses: ./
    - name: Clone NativeScript Demo App
      run: git clone https://github.com/NativeScript/nativescript-marketplace-demo
    - name: Install dependencies
      run: sudo npm install
      working-directory: nativescript-marketplace-demo
    - name: Build NativeScript Demo App
      run: tns build android
      working-directory: nativescript-marketplace-demo

  testDemoAndroidWindows:
    name: Build Android on windows-latest
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
    - name: Clone NativeScript Demo App
      run: git clone https://github.com/NativeScript/nativescript-marketplace-demo
    - name: Install dependencies
      run: npm install
      working-directory: nativescript-marketplace-demo
    - name: Build NativeScript Demo App
      run: tns build android
      working-directory: nativescript-marketplace-demo

  testDemoiOS:
    name: Build iOS on MacOSX
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
    - name: Clone NativeScript Demo App
      run: git clone https://github.com/NativeScript/nativescript-marketplace-demo
    - name: Install dependencies
      run: npm install
      working-directory: nativescript-marketplace-demo
    - name: Build NativeScript Demo App
      run: tns build ios
      working-directory: nativescript-marketplace-demo
          